repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/pycqa/isort
    rev: '5.8.0'
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: '22.10.0'
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    - id: mypy
      additional_dependencies:
      - pydantic~=1.8.2
      exclude: >
        (?x)^(
            docs/.*|
            tests/.*|
            conftest.py
        )$

  - repo: https://github.com/PyCQA/pylint
    rev: v2.8.3
    hooks:
    - id: pylint
      additional_dependencies:
      - aiida-core~=2.0
      - fastapi~=0.65.1
      - uvicorn[standard]~=0.19.0
      - pydantic~=1.8.2
      - graphene<3
      - lark
      - python-dateutil~=2.0
      - python-jose
      - python-multipart
      - passlib
      - pytest~=3.6,<5.0.0
      - sphinx<4
      exclude: >
        (?x)^(
            docs/.*|
        )$
