# Install pre-commit hooks via:
# pre-commit install
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
      - id: check-yaml

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.46"
    hooks:
    - id: check-manifest
      args: [--no-build-isolation]
      additional_dependencies: [setuptools>=46.4.0, "reentry"]

  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
    - id: mypy
      additional_dependencies:
      - pydantic~=1.8.2
      exclude: >
        (?x)^(
            docs/.*|
            tests/.*|
            conftest.py
        )$

  - repo: https://github.com/PyCQA/pylint
    rev: v2.8.3
    hooks:
    - id: pylint
      additional_dependencies:
      - aiida-core>=1.6,<2.0.0
      - sqlalchemy<1.4
      - fastapi~=0.65.1
      - uvicorn[standard]>=0.12.0,<0.14.0
      - pydantic~=1.8.2
      - graphene<3
      - lark
      - python-jose
      - python-multipart
      - passlib
      - pytest~=3.6,<5.0.0
      - sphinx<4
      - importlib_metadata~=4.3
      exclude: >
        (?x)^(
            docs/.*|
        )$

  - repo: local
    hooks:
    - id: version-number
      name: Check version numbers
      entry: python ./.github/check_version.py ./setup.json ./aiida_restapi/__init__.py
      language: python
      language_version: python3
      pass_filenames: false
      files: "^(setup.json)|(aiida_restapi/__init__.py)"
