repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
    exclude: &exclude_pre_commit_hooks >
      (?x)^(
        tests/.*(?<!\.py)$|
        docs/source/.+\.aiida/repo/.+|
        CHANGELOG.md|
      )$
  - id: fix-encoding-pragma
    args: [--remove]
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
    exclude: *exclude_pre_commit_hooks

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.0
  hooks:
  - id: mypy
    additional_dependencies:
    - pydantic~=2.0
    - types-python-dateutil
    - types-docutils
    exclude: >
      (?x)^(
          docs/.*|
          examples/.*|
          tests/.*|
          conftest.py
      )$

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.6
  hooks:
  - id: check-github-workflows

- repo: https://github.com/ikamensh/flynt/
  rev: 1.0.1
  hooks:
  - id: flynt
    args: [--line-length=120, --fail-on-change]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
  - id: ruff-format
    exclude: &exclude_ruff >
      (?x)^(
        docs/source/topics/processes/include/snippets/functions/parse_docstring_expose_ipython.py|
        docs/source/topics/processes/include/snippets/functions/signature_plain_python_call_illegal.py|
      )$
  - id: ruff
    exclude: *exclude_ruff
    args: [--fix, --exit-non-zero-on-fix, --show-fixes]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.13.0
  hooks:
  - id: pretty-format-toml
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: >-
      (?x)^(
        tests/.*|
        environment.yml|
      )$
